name: 'Denil'
description: 'Remove labels from PR based on whether are already present'
author: 'Denil'
inputs:
  separator:
    required: true
    description: 'Separator to be used to extract label names from the input'
  labels-list:
    required: true
    description: 'A string of all labels that are to be checked with, separated with the passed separator'
  issue-number:
    required: true
    description: 'Issue number'
  token:
    required: true
    description: 'Github token'
runs:
  using: 'node16'
  main: 'dist/index.js'
